### ISSUE TITLE
New provider Cloudflare (cf)

### ISSUE THREAD

**Issue by samip5** [cloudydeno/kubernetes-dns-sync#4]
I would like to also request Cloudflare support.

**Comment by danopia** [comment]
I've added this to the zone provider board. It could happen in the next week but no promises yet.

**Comment by danopia** [comment]
Any thoughts about "Proxy status"? I understand that external-dns lets you set a default (yes/no) at a provider level and then each source resource can override that with an annotation. Should I just yank that 1:1?

**Comment by samip5** [comment]
It should be with a toggle (via annotation) of some sorts aswell as a default too.
